version: "3.7"

services:
  # https://hub.docker.com/_/traefik
  traefik:
    image: traefik:2.1.6
    restart: unless-stopped
    container_name: traefik
    hostname: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA}/traefik-config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${DATA}/traefik-config/acme.json:/etc/traefik/acme.json
      - ${DATA}/traefik-config/access.log:/etc/traefik/access.log
      - ${DATA}/traefik-config/config.yml:/etc/traefik/config.yml:ro
    environment:
      DO_AUTH_TOKEN: ${DO_TOKEN}
    labels:
      - "traefik.enable=true"
      # http catch-all
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      # https
      - "traefik.http.routers.traefik.entrypoints=web-secure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_TLD}`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.tls.domains[0].main=*.${DOMAIN_TLD}"
      - "traefik.http.routers.traefik.tls.options=default"
      # middlewares
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${USER}:${PASSWORD}"
      - "traefik.http.routers.traefik.middlewares=secured@file, traefik-auth"
      # services
      - "traefik.http.routers.traefik.service=api@internal"

  # https://hub.docker.com/_/nextcloud
  nextcloud:
    image: nextcloud:18.0.2
    restart: unless-stopped
    container_name: nextcloud
    hostname: nextcloud
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - dbs
    depends_on:
      - db
      - redis
      - documentserver
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/nextcloud-main:/var/www/html
      - ${DATA}/nextcloud-apps:/var/www/html/custom_apps
      - ${DATA}/nextcloud-config:/var/www/html/config
      - ${DATA}/nextcloud-data:/var/www/html/data
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: "cloud.${DOMAIN_TLD}"
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nextcloud
      POSTGRES_USER: superUser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: "db:5432"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # https
      - "traefik.http.routers.nextcloud.entrypoints=web-secure"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAIN_TLD}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud.tls.domains[0].main=*.${DOMAIN_TLD}"
      - "traefik.http.routers.nextcloud.tls.options=default"
      # middlewares
      - "traefik.http.routers.nextcloud.middlewares=security-headers@file, nextcloud-redirect@file"
      # services
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

  # https://hub.docker.com/r/onlyoffice/documentserver
  documentserver:
    image: onlyoffice/documentserver
    restart: unless-stopped
    container_name: documentserver
    hostname: documentserver
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - dbs
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/ds-logs:/var/log/onlyoffice
      - ${DATA}/ds-cache:/var/lib/onlyoffice
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: ${OFFICE_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # https
      - "traefik.http.routers.documentserver.entrypoints=web-secure"
      - "traefik.http.routers.documentserver.rule=Host(`documentserver.${DOMAIN_TLD}`)"
      - "traefik.http.routers.documentserver.tls=true"
      - "traefik.http.routers.documentserver.tls.certresolver=letsencrypt"
      - "traefik.http.routers.documentserver.tls.domains[0].main=*.${DOMAIN_TLD}"
      - "traefik.http.routers.documentserver.tls.options=default"
      # middlewares
      - "traefik.http.routers.documentserver.middlewares=security-headers@file"
      # services
      - "traefik.http.routers.documentserver.service=documentserver"
      - "traefik.http.services.documentserver.loadbalancer.server.port=80"

  # https://hub.docker.com/_/postgres
  db:
    image: postgres:12.2
    restart: unless-stopped
    container_name: db
    hostname: db
    security_opt:
      - no-new-privileges:true
    networks:
      - dbs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: superUser
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  # https://hub.docker.com/_/redis
  redis:
    image: redis:5.0.7
    restart: unless-stopped
    container_name: redis
    hostname: redis
    security_opt:
      - no-new-privileges:true
    networks:
      - dbs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/redis-db:/bitnami/redis/data
      - ${DATA}/redis-config:/opt/bitnami/redis/etc/redis.conf
    environment:
      REDIS_PASSWORD: ${DB_PASSWORD}

  # https://hub.docker.com/r/jellyfin/jellyfin
  jellyfin:  
    image: jellyfin/jellyfin:10.5.0
    restart: unless-stopped
    container_name: jellyfin
    hostname: jellyfin
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/jellyfin-config:/config
      - ${DATA}/jellyfin-cache:/cache
      - ${DATA}/nextcloud-data:/media:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # https
      - "traefik.http.routers.jellyfin.entrypoints=web-secure"
      - "traefik.http.routers.jellyfin.rule=Host(`media.${DOMAIN_TLD}`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jellyfin.tls.domains[0].main=*.${DOMAIN_TLD}"
      - "traefik.http.routers.jellyfin.tls.options=default"
      # middlewares
      - "traefik.http.routers.jellyfin.middlewares=security-headers@file"
      # services
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  # https://hub.docker.com/r/bitwardenrs/server
  bitwarden:
    image: bitwardenrs/server:1.13.1
    restart: unless-stopped
    container_name: bitwarden
    hostname: bitwarden
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ${DATA}/bw-data:/data
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # UI
      # https
      - "traefik.http.routers.bitwarden-ui.entrypoints=web-secure"
      - "traefik.http.routers.bitwarden-ui.rule=Host(`vault.${DOMAIN_TLD}`)"
      - "traefik.http.routers.bitwarden-ui.tls=true"
      - "traefik.http.routers.bitwarden-ui.tls.certresolver=letsencrypt"
      - "traefik.http.routers.bitwarden-ui.tls.domains[0].main=*.${DOMAIN_TLD}"
      - "traefik.http.routers.bitwarden-ui.tls.options=default"
      # middlewares
      - "traefik.http.routers.bitwarden-ui.middlewares=security-headers@file"
      # services
      - "traefik.http.routers.bitwarden-ui.service=bitwarden-ui"
      - "traefik.http.services.bitwarden-ui.loadbalancer.server.port=80"
      # WEBSOCKET
      # https
      - "traefik.http.routers.bitwarden-websocket.entrypoints=web-secure"
      - "traefik.http.routers.bitwarden-websocket.rule=Host(`vault.${DOMAIN_TLD}`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket.tls=true"
      - "traefik.http.routers.bitwarden-websocket.tls.certresolver=letsencrypt"
      - "traefik.http.routers.bitwarden-websocket.tls.domains[0].main=*.${DOMAIN_TLD}"
      - "traefik.http.routers.bitwarden-websocket.tls.options=default"
      # middlewares
      - "traefik.http.routers.bitwarden-websocket.middlewares=security-headers@file"
      # services
      - "traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket"
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"

networks:
  proxy:
    external: true
  dbs:
    external: true
