version: "3.7"

services:
  # https://hub.docker.com/r/bitwardenrs/server
  bitwarden:
    image: bitwardenrs/server:1.13.1
    restart: unless-stopped
    container_name: bitwarden
    hostname: bitwarden
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ${DATA}/bw-data:/data
    environment:
      ADMIN_TOKEN: ${TOKEN}
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # UI
      # https
      - "traefik.http.routers.bitwarden-ui.entrypoints=web-secure"
      - "traefik.http.routers.bitwarden-ui.rule=Host(`bitwarden.${DOMAIN_TLD}`)"
      - "traefik.http.routers.bitwarden-ui.tls=true"
      - "traefik.http.routers.bitwarden-ui.tls.certresolver=letsencrypt"
      - "traefik.http.routers.bitwarden-ui.tls.domains[0].main=*.${DOMAIN_TLD}"
      - "traefik.http.routers.bitwarden-ui.tls.options=default"
      # middlewares
      - "traefik.http.routers.bitwarden-ui.middlewares=security-headers@file"
      # services
      - "traefik.http.routers.bitwarden-ui.service=bitwarden-ui"
      - "traefik.http.services.bitwarden-ui.loadbalancer.server.port=80"
      # WEBSOCKET
      # https
      - "traefik.http.routers.bitwarden-websocket.entrypoints=web-secure"
      - "traefik.http.routers.bitwarden-websocket.rule=Host(`bitwarden.${DOMAIN_TLD}`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket.tls=true"
      - "traefik.http.routers.bitwarden-websocket.tls.certresolver=letsencrypt"
      - "traefik.http.routers.bitwarden-websocket.tls.domains[0].main=*.${DOMAIN_TLD}"
      - "traefik.http.routers.bitwarden-websocket.tls.options=default"
      # middlewares
      - "traefik.http.routers.bitwarden-websocket.middlewares=security-headers@file"
      # services
      - "traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket"
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"

networks:
  proxy:
    external: true
