http:
  middlewares:
    security-networks:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/24"
        - "192.168.0.0/16"
        - "172.0.0.0/8"
        - "192.168.1.0/24"

    security-headers:
      headers:
        referrerPolicy: no-referrer
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        sslRedirect: true
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          X-Powered-By: "Redstone"
          Server: "Server"

    nextcloud-redirect:
      redirectRegex:
        permanent: true
        regex: http://(.*)/.well-known/(card|cal)dav
        replacement: http://$$1/remote.php/dav/

    secured:
      chain:
        middlewares:
        - security-networks
        - security-headers
