version: "3.7"

services:
  # https://hub.docker.com/_/traefik
  traefik:
    image: traefik:2.1.6
    restart: unless-stopped
    container_name: traefik
    hostname: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA}/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${DATA}/acme.json:/etc/traefik/acme.json
      - ${DATA}/access.log:/etc/traefik/access.log
      - ${DATA}/config.yml:/etc/traefik/config.yml:ro
    environment:
      DO_AUTH_TOKEN: ${DO_TOKEN}
    labels:
      - "traefik.enable=true"
      # http catch-all
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      # https
      - "traefik.http.routers.traefik-secure.entrypoints=web-secure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN_TLD}`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=*.${DOMAIN_TLD}"
      - "traefik.http.routers.traefik-secure.tls.options=default"
      # middlewares
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${USER}:${PASSWORD}"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth, secured@file"
      # services
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true
