## Dynamic configuration
http:

  routers:
    https-redirect:
      entryPoints:
        - http
      middlewares:
        - https-redirect
      rule: "HostRegexp(`{host:[a-z-.]+}`)"
      service: noop
      priority: 20

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https

    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true

    security-networks:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/24"
        - "192.168.0.0/16"
        - "172.0.0.0/8"
        - "192.168.1.0/24"

    secured:
      chain:
        middlewares:
        - security-networks
        - security-headers

    secured-auth:
      chain:
        middlewares:
        - security-networks
        - security-headers
        - auth@docker

  services:
      noop:
        loadBalancer:
          servers:
            - url: "http://127.0.0.1"