version: "3.7"

services:
  # https://hub.docker.com/_/nextcloud
  nextcloud:
    build: .
    restart: unless-stopped
    container_name: nextcloud
    hostname: nextcloud
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - dbs
    depends_on:
      - db
      - redis
      - documentserver
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/nextcloud-main:/var/www/html
      - ${DATA}/nextcloud-apps:/var/www/html/custom_apps
      - ${DATA}/nextcloud-config:/var/www/html/config
      - ${DATA}/nextcloud-data:/var/www/html/data
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.${DOMAIN_TLD}"
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nextcloud
      POSTGRES_USER: superUser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: "db:5432"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # https
      - "traefik.http.routers.nextcloud.entrypoints=web-secure"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN_TLD}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud.tls.domains[0].main=*.${DOMAIN_TLD}"
      - "traefik.http.routers.nextcloud.tls.options=default"
      # middlewares
      - "traefik.http.routers.nextcloud.middlewares=security-headers@file, nextcloud-redirect@file"
      # services
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

  # https://hub.docker.com/r/onlyoffice/documentserver
  documentserver:
    image: onlyoffice/documentserver
    restart: unless-stopped
    container_name: documentserver
    hostname: documentserver
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - dbs
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/ds-logs:/var/log/onlyoffice
      - ${DATA}/ds-cache:/var/lib/onlyoffice
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: ${PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # https
      - "traefik.http.routers.documentserver.entrypoints=web-secure"
      - "traefik.http.routers.documentserver.rule=Host(`documentserver.${DOMAIN_TLD}`)"
      - "traefik.http.routers.documentserver.tls=true"
      - "traefik.http.routers.documentserver.tls.certresolver=letsencrypt"
      - "traefik.http.routers.documentserver.tls.domains[0].main=*.${DOMAIN_TLD}"
      - "traefik.http.routers.documentserver.tls.options=default"
      # middlewares
      - "traefik.http.routers.documentserver.middlewares=security-headers@file"
      # services
      - "traefik.http.routers.documentserver.service=documentserver"
      - "traefik.http.services.documentserver.loadbalancer.server.port=80"

  # https://hub.docker.com/_/postgres
  db:
    image: postgres:12.2
    restart: unless-stopped
    container_name: db
    hostname: db
    security_opt:
      - no-new-privileges:true
    networks:
      - dbs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: superUser
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  # https://hub.docker.com/_/redis
  redis:
    image: redis:5.0.7
    restart: unless-stopped
    container_name: redis
    hostname: redis
    security_opt:
      - no-new-privileges:true
    networks:
      - dbs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/redis-db:/bitnami/redis/data
      - ${DATA}/redis-config:/opt/bitnami/redis/etc/redis.conf
    environment:
      REDIS_PASSWORD: ${DB_PASSWORD}

networks:
  proxy:
    external: true
  dbs:
    external: true