version: "3.7"

services:
  # https://hub.docker.com/_/nextcloud
  nextcloud:
    image: nextcloud:18.0.1
    restart: unless-stopped
    container_name: nextcloud
    hostname: nextcloud
    networks:
      - proxy
    depends_on:
      - db
      - redis
    volumes:
      - ${DATA}/nextcloud-main:/var/www/html
      - ${DATA}/nextcloud-apps:/var/www/html/custom_apps
      - ${DATA}/nextcloud-config:/var/www/html/config
      - ${DATA}/nextcloud_data:/var/www/html/data
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.${DOMAIN_TLD}"
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nextcloud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: "db:5432"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN_TLD}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      # middleware
      - "traefik.http.routers.nextcloud.middlewares=secured-nextcloud@file"
      # services
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"

  # https://hub.docker.com/_/postgres
  db:
    image: postgres:12.2
    restart: unless-stopped
    container_name: db
    hostname: db
    networks:
      - proxy
    volumes:
      - ${DATA}/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${PASSWORD}
  
  # https://hub.docker.com/_/redis
  redis:
    image: redis:5.0.7
    restart: unless-stopped
    container_name: redis
    hostname: redis
    networks:
      - proxy
    volumes:
      - ${DATA}/redis-db:/bitnami/redis/data
      - ${DATA}/redis-config:/opt/bitnami/redis/etc/redis.conf
    environment:
      REDIS_PASSWORD: ${DB_PASSWORD}

networks:
  proxy:
    external: true