version: "3.7"

services:
  # https://hub.docker.com/_/nextcloud
  nextcloud:
      build: .
      restart: unless-stopped
      container_name: nextcloud
      hostname: nextcloud
      security_opt:
        - no-new-privileges:true
      networks:
        - proxy
      depends_on:
        - db
        - redis
        - documentserver
      volumes:
        - ${DATA}/nextcloud-main:/var/www/html
        - ${DATA}/nextcloud-apps:/var/www/html/custom_apps
        - ${DATA}/nextcloud-config:/var/www/html/config
        - ${DATA}/nextcloud-data:/var/www/html/data
      environment:
        NEXTCLOUD_TRUSTED_DOMAINS: "cloud.${DOMAIN_TLD}"
        REDIS_HOST: redis
        REDIS_HOST_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: nextcloud
        POSTGRES_USER: superUser
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_HOST: "db:5432"

    # https://hub.docker.com/r/onlyoffice/documentserver
    documentserver:
      image: onlyoffice/documentserver
      restart: unless-stopped
      container_name: documentserver
      hostname: documentserver
      networks:
        - proxy
      depends_on:
        - db
      volumes:
        - ${DATA}/ds-logs:/var/log/onlyoffice
        - ${DATA}/ds-cache:/var/lib/onlyoffice
      environment:
        JWT_ENABLED: "true"
        JWT_SECRET: ${PASSWORD}

    # https://hub.docker.com/_/postgres
    db:
      image: postgres:12.2
      restart: unless-stopped
      container_name: db
      hostname: db
      networks:
        - proxy
      volumes:
        - ${DATA}/db-data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: superUser
        POSTGRES_PASSWORD: ${DB_PASSWORD}

    # https://hub.docker.com/_/redis
    redis:
      image: redis:5.0.7
      restart: unless-stopped
      container_name: redis
      hostname: redis
      networks:
        - proxy
      environment:
        REDIS_PASSWORD: ${DB_PASSWORD}
      volumes:
        - ${DATA}/redis-db:/bitnami/redis/data
        - ${DATA}/redis-config:/opt/bitnami/redis/etc/redis.conf
      